name: CDK Deployment

on:
  push:
    branches:
      - main

env:
    AWS_REGION : "eu-central-1"

# permission can be added at job level or workflow level
permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_DEV }}
          role-session-name: github-action-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # The following message update step does not accept a channel name.
          # Setting a channel ID here for consistency is highly recommended.
          payload: |
            {
              "text": "Deployment started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                },
                {
                  "fallback": "Would you recommend it to customers?",
                  "title": "Would you recommend it to customers?",
                  "callback_id": "comic_1234_xyz",
                  "color": "#3AA3E3",
                  "attachment_type": "default",
                  "actions": [
                      {
                          "name": "recommend",
                          "text": "Recommend",
                          "type": "button",
                          "value": "recommend"
                      },
                      {
                          "name": "no",
                          "text": "No",
                          "type": "button",
                          "value": "bad"
                      }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEPLOYMENT_SLACK_WEBHOOK }}

      - name: Synth
        run: yarn cdk synth

      - name: Upload template
        run: >
          aws s3 cp cdk.out/ s3://${{ vars.TEMPLATE_BUCKET }}/${{ github.sha }}/ \
            --recursive \
            --exclude "*" \
            --include "*.assets.json" \
            --include "*.template.json"

      - name: Create diff
        run: yarn cdk diff

      - uses: slackapi/slack-github-action@v1.24.0
        with:
          # Unlike the step posting a new message, this step does not accept a channel name.
          # Please use a channel ID, not a name here.
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Completed)",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEPLOYMENT_SLACK_WEBHOOK}}


  deploy:
    runs-on: ubuntu-latest
    needs: "diff"
    environment: production
    concurrency:
      group: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_DEV }}
          role-session-name: github-action-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        run: yarn cdk deploy