name: CDK Deployment

on:
  push:
    branches:
      - main

env:
    AWS_REGION : "eu-central-1"

# permission can be added at job level or workflow level
permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_DEV }}
          role-session-name: github-action-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'cdk-deployments'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Synth
        run: yarn cdk synth

      - name: Upload template
        run: >
          aws s3 cp cdk.out/ s3://${{ vars.TEMPLATE_BUCKET }}/${{ github.sha }}/ \
            --recursive \
            --exclude "*" \
            --include "*.assets.json" \
            --include "*.template.json"

      - name: Create diff
        run: yarn cdk diff

      # - name: Send diff to slack
      #   run: |
      #     # Update Slack message with completion status
      #     curl -X POST -H 'Content-type: application/json' --data '{
      #       "text": "The workflow run is completed!",
      #       "attachments": [
      #         {
      #           "fallback": "Workflow completed",
      #           "text": "The workflow has finished successfully."
      #         }
      #       ]
      #     }' ${{ secrets.DEPLOYMENT_SLACK_WEBHOOK }}/$timestamp


  deploy:
    runs-on: ubuntu-latest
    needs: "diff"
    environment: production
    concurrency:
      group: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_DEV }}
          role-session-name: github-action-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        run: yarn cdk deploy