name: CDK Deployment

on:
  push:
    branches:
      - main

env:
    AWS_REGION : "eu-central-1"

# permission can be added at job level or workflow level
permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_DEV }}
          role-session-name: github-action-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Send Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Deploy CDK on commit ${{ github.sha }}",
            "attachments": [
              {
                "fallback": "Review the workflow run",
                "text": "Click the button below to review the workflow run.",
                "callback_id": "review_workflow_run",
                "actions": [
                  {
                    "name": "review",
                    "text": "Review",
                    "type": "button",
                    "value": "${{ github.run_id }}"
                  }
                ]
              }
            ]
          }' ${{ secrets.DEPLOYMENT_SLACK_WEBHOOK }}

      - name: Synth
        run: yarn cdk synth

      - name: Upload template
        run: >
          aws s3 cp cdk.out/ s3://${{ vars.TEMPLATE_BUCKET }}/${{ github.sha }}/ \
            --recursive \
            --exclude "*" \
            --include "*.assets.json" \
            --include "*.template.json"

      - name: Create diff
        run: yarn cdk diff


  deploy:
    runs-on: ubuntu-latest
    needs: "diff"
    environment: production
    concurrency:
      group: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_DEV }}
          role-session-name: github-action-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        run: yarn cdk deploy