name: CDK Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::718517280342:role/OidcIntegrationStack-ActualRoleC982540D-1N6ISVGB3079
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Create diff
        run: yarn cdk diff

      - name: Deploy
        run: npx cdk deploy